### ISSUE TITLE
fix it

### ISSUE THREAD

**Issue by kleen** [pzhgugu/goshop#2]
1 org.csource.fastdfs 没有jar ，我下载源码，打成jar， 结果又发现缺少这个方法，  
              storageClient.upload_appender_file(data,type,metaList);
    能否上传一个完整一点的代码上来。

**Comment by suichunyu** [comment]
替换一下
<dependency>
                <groupId>com.github.tobato</groupId>
                <artifactId>fastdfs-client</artifactId>
                <version>1.25.1-RELEASE</version>
            </dependency>

**Comment by suichunyu** [comment]
`<dependency>
                <groupId>com.github.tobato</groupId>
                <artifactId>fastdfs-client</artifactId>
                <version>1.25.1-RELEASE</version>
            </dependency>`

**Comment by ghost** [comment]
替换一下
`<dependency>
                <groupId>com.github.tobato</groupId>
                <artifactId>fastdfs-client</artifactId>
                <version>1.25.1-RELEASE</version>
            </dependency>`
